use company_db;

SELECT * FROM S
WHERE Status = (SELECT Status FROM S WHERE Sname = 'CLARK');

SELECT * FROM SEMP
WHERE DEPTNO = (SELECT DEPTNO FROM SEMP WHERE EMPNAME = 'MILLER');

SELECT * FROM P
WHERE Weight > (SELECT MAX(Weight) FROM P WHERE Color = 'Red');

SELECT * FROM J
WHERE City = (SELECT City FROM J WHERE Jname = 'TAPE');

SELECT * FROM P
WHERE Weight < (SELECT MIN(Weight) FROM P WHERE Color = 'Green');

SELECT S.Sname 
FROM S
JOIN SPJ ON S.`S#` = SPJ.`S#`
ORDER BY SPJ.Qty DESC
LIMIT 1;

SELECT EMPNAME 
FROM SEMP
ORDER BY BASIC ASC
LIMIT 1;

SELECT S.Sname
FROM S
JOIN SPJ ON S.`S#` = SPJ.`S#`
GROUP BY S.Sname
ORDER BY SUM(SPJ.Qty) DESC
LIMIT 1;

SELECT D.DEPTNAME
FROM SDEPT D
JOIN SEMP E ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNAME
ORDER BY COUNT(E.EMPNO) DESC
LIMIT 1;
